version: 2
jobs:
  test-static:
      docker:
        - image: circleci/python:3.6
          user: circleci
      steps:
        - checkout
        - run:
            name: Flake8 and complexity
            command: |
              python3 -m venv venv
              source venv/bin/activate
              pip install -r tests/requirements-flake8.txt
              flake8 djenvrep
              radon cc --min B drfdapc
              radon mi --min B drfdapc
              lizard -l python -w drfdapc

  test-django-latest-py-3.6:
      docker:
        - image: circleci/python:3.6
          user: circleci
      steps:
        - checkout
        - run:
            name: Latest Django with Python 3.6
            command: |
              python3 -m venv venv
              source venv/bin/activate
              pip install -r tests/requirements.txt
              coverage run manage.py test

  test-django-2.0-py-3.6:
      docker:
        - image: circleci/python:3.6
          user: circleci
      steps:
        - checkout
        - run:
            name: Django 2.0 with Python 3.6
            command: |
              python3 -m venv venv
              source venv/bin/activate
              pip install -r tests/requirements-dj20.txt
              coverage run manage.py test
              codecov

  test-django-1.11-py-3.6:
      docker:
        - image: circleci/python:3.6
          user: circleci
      steps:
        - checkout
        - run:
            name: Django 1.11 with Python 3.6
            command: |
              python3 -m venv venv
              source venv/bin/activate
              pip install -r tests/requirements-dj111.txt
              coverage run manage.py test

  test-django-1.11-py-3.5:
      docker:
        - image: circleci/python:3.5
          user: circleci
      steps:
        - checkout
        - run:
            name: Django 1.11 with Python 3.5
            command: |
              python3 -m venv venv
              source venv/bin/activate
              pip install -r tests/requirements-dj111.txt
              coverage run manage.py test

  test-django-1.11-py-3.4:
      docker:
        - image: circleci/python:3.4
          user: circleci
      steps:
        - checkout
        - run:
            name: Django 1.11 with Python 3.4
            command: |
              python3 -m venv venv
              source venv/bin/activate
              pip install -r tests/requirements-dj111.txt
              coverage run manage.py test

  test-django-1.11-py-2.7:
      docker:
        - image: circleci/python:2.7
          user: circleci
      steps:
        - checkout
        - run:
            name: Django 1.11 with Python 2.7
            command: |
              virtualenv venv
              source venv/bin/activate
              pip install -r tests/requirements-dj111.txt
              coverage run manage.py test

  test-django-1.8-py-2.7:
      docker:
        - image: circleci/python:2.7
          user: circleci
      steps:
        - checkout
        - run:
            name: Django 1.8 with Python 2.7
            command: |
              virtualenv venv
              source venv/bin/activate
              pip install -r tests/requirements-dj18.txt
              coverage run manage.py test

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-django-latest-py-3.6
      - test-django-2.0-py-3.6
      - test-django-1.11-py-3.6
      - test-django-1.11-py-3.5
      - test-django-1.11-py-3.4
      - test-django-1.11-py-2.7
      - test-django-1.8-py-2.7
      - test-static
